---
title: "Team analytics with cricketr"
output:
  html_document: default
  word_document: default
---

*I can't sit still and see another man slaving and working. I want to get up and superintend, and walk round with my hands in my pockets, and tell him what to do. It is my energetic nature. I can't help it.*

*It always does seem to me that I am doing more work than I should do. It is not that I object to the work, mind you; I like work: it fascinates me. I can sit and look at it for hours. I love to keep it by me: the idea of getting rid of it nearly breaks my heart.*

*Let your boat of life be light, packed with only what you need - a homely home and simple pleasures, one or two friends, worth the name, someone to love and someone to love you, a cat, a dog, and a pipe or two, enough to eat and enough to wear, and a little more than enough to drink; for thirst is a dangerous thing. *


                    Three Men in a boat by Jerome K Jerome
                    
## Introduction
 **Cricpy**, the python avatar of my R package was born about a 9 months back see [Introducing cricpy:A python package to analyze performances of cricketers](https://gigadom.in/2018/10/28/introducing-cricpya-python-package-to-analyze-performances-of-cricketrs/). Cricpy, like its R twin, can analyze performance of batsmen & bowlers in Test, ODI and T20 formats.  Now, in the latest release of cricpy, I have included 8 functions which can perform Team analytics. Team performance analysis can be done for Test, ODI and T20 matches.

This package uses the statistics info available in ESPN Cricinfo Statsguru. The current version of this package can handle all formats of the game including Test, ODI and Twenty20 cricket.

You should be able to install the package using *pip install cricpy*. Please be mindful of  [ESPN Cricinfo Terms of Use](http://www.espncricinfo.com/ci/content/site/company/terms_use.html)

There are 5 functions which are used internally
1) getTeamData b) getTeamNumber c) getMatchType d) getTeamDataHomeAway e) cleanTeamData

and the external functions which
a) teamWinLossStatusVsOpposition
b) teamWinLossStatusAtGrounds
c) plotTimelineofWinsLosses

All the above functions are common to Test, ODI and T20 teams

The data for a particular Team can be obtained with the getTeamDataHomeAway() function from the package. This will return a dataframe of the team's win/loss status at home and away venues over a period of time.
This can be saved as a CSV file. Once this is done, you can use this CSV file for all subsequent analysis

As before you can get the help for any of the cricpy functions as below
```{python}
import cricpy.analytics as ca
#help(ca.teamWinLossStatusAtGrounds)
```

##1. Get team data 
###1a. Test
The teams in Test cricket are included below

1. Afghanistan  2.Bangladesh 3.  England 4. World 5. India 6. Ireland 7. New Zealand  8. Pakistan 9. South Africa 10.Sri Lanka 11. West Indies 12.Zimbabwe  

You can use this for the teamName paramater. This will return a dataframe and also save the file as a CSV , if save=True

**Note**: - Since I have already got the data as CSV files I am not executing the lines below
```{python}
# Get the data for the teams. Save as CSV
#indiaTest= getTeamDataHomeAway(dir=".",teamView="bat",matchType="Test",file="indiaTest.csv",save=True,teamName="India")
#getTeamDataHomeAway(teamName="South Africa", matchType="Test", file="southafricaTest.csv", save=True)
#getTeamDataHomeAway(teamName="West Indies", matchType="Test", file="westindiesTest.csv", save=True)
#newzealandTest = getTeamDataHomeAway(matchType="Test",file="newzealandTest.csv",save=True,teamName="New Zealand")
```

###1b.  ODI
The ODI teams in the world are below. The data for these teams can be got by names as shown below

1. Afghanistan 2. Africa XI    3. Asia XI    4.Australia    5.Bangladesh    
6. Bermuda 7. England    8. ICC World X1  9. India 11.Ireland  12. New Zealand
13. Pakistan 14. South Africa  15.Sri Lanka 17. West Indies 18. Zimbabwe
19. Canada 21. East Africa 22. Hong Kong 23.Ireland 24. Kenya  25. Namibia
26. Nepal 27.Netherlands 28. Oman 29.Papua New Guinea 30.  Scotland
31. United Arab Emirates 32. United States of America 
```{python}
#indiaODI=  getTeamDataHomeAway(dir=".",matchType="ODI",file="indiaODI.csv",save=True,teamName="India")
#englandODI =  getTeamDataHomeAway(matchType="ODI",file="englandODI.csv",save=True,teamName="England")
#westindiesODI = getTeamDataHomeAway(matchType="ODI",file="westindiesODI.csv",save=True,teamName="West Indies")
#irelandODI <- getTeamDataHomeAway(matchType="ODI",file="irelandODI.csv",save=True,teamName="Ireland")
```


###1c T20
The T20 teams in the world are 
                 
1. Afghanistan 2. Australia 3. Bahrain 4. Bangladesh 5. Belgium 6. Belize 
7. Bermuda 8.Botswana 9.  Canada 11. Costa Rica 12. Germany 13. Ghana
14. Guernsey 15. Hong Kong 16. ICC World X1 17.India 18. Ireland 19.Italy
20. Jersey 21. Kenya   22.Kuwait    23.Maldives   24.Malta    25.Mexico   26.Namibia  
27.Nepal   28.Netherlands 29. New Zealand   30.Nigeria  31.Oman  32. Pakistan  
33.Panama   34.Papua New Guinea  35. Philippines  36.Qatar  37.Saudi Arabia  
38.Scotland  39.South Africa  40.Spain   41.Sri Lanka  42.Uganda   43.United Arab Emirates   United States of America 44.Vanuatu  45.West Indies

```python 
#southafricaT20 = getTeamDataHomeAway(matchType="T20",file="southafricaT20.csv",save=True,teamName="South Africa")
#srilankaT20 = getTeamDataHomeAway(matchType="T20",file="srilankaT20.csv",save=True,teamName="Sri Lanka")
#canadaT20 = getTeamDataHomeAway(matchType="T20",file="canadaT20.csv",save=True,teamName="Canada")
#afghanistanT20 = getTeamDataHomeAway(matchType="T20",file="afghanistanT20.csv",save=True,teamName="Afghanistan")
```
##2  Analysis of Test matches
The functions below perform analysis of Test teams

##2a. Wins vs Loss against opposition
This function performs analysis of Test teams against other teams at home/away or neutral venue.
**Note**:- The opposition can be a list of opposition teams. Similarly homeOrAway can also be a list of home/away/neutral venues.



```{python opposition1,cache=TRUE,fig.width=10}
import cricpy.analytics as ca
# Get the performance of Indian test team against all teams at all venues as a dataframe
df =ca.teamWinLossStatusVsOpposition("indiaTest.csv",teamName="India",opposition=["all"], homeOrAway=["all"], matchType="Test", plot=False)
print(df)

# Plot the performance of Indian Test team  against all teams at all venues
ca.teamWinLossStatusVsOpposition("indiaTest.csv",teamName="India",opposition=["all"],homeOrAway=["all"],matchType="Test",plot=True)

# Get the performance of Australia against India, England and New Zealand at all venues in Tests
df =ca.teamWinLossStatusVsOpposition("southafricaTest.csv",teamName="South Africa",opposition=["India","England","New Zealand"],homeOrAway=["all"],matchType="Test",plot=False)
print(df)

#Plot the performance of Australia against England, India and New Zealand only at home (Australia) 
ca.teamWinLossStatusVsOpposition("southafricaTest.csv",teamName="South Africa",opposition=["India","England","New Zealand"],homeOrAway=["home","away"],matchType="Test",plot=True)


```


### 2b Wins vs losses of Test teams against opposition at different venues
```{python ground1,cache=TRUE}
import cricpy.analytics as ca
# Get the  performance of Pakistan against India, West Indies, South Africa at all venues in Tests and show performances at the venues
df = ca.teamWinLossStatusAtGrounds("westindiesTest.csv",teamName="West Indies",opposition=["India","Sri Lanka","South Africa"],homeOrAway=["all"],matchType="Test",plot=False)
print(df)

# Plot the performance of New Zealand Test team against England, Sri Lanka and Bangladesh at all grounds playes 
ca. teamWinLossStatusAtGrounds("newzealandTest.csv",teamName="New Zealand",opposition=["England","Sri Lanka","Bangladesh"],homeOrAway=["all"],matchType="Test",plot=True)
```


###2c. Plot the time line of wins vs losses of Test teams against opposition at different venues during an interval
```{python timeline1,cache=TRUE }
import cricpy.analytics as ca
# Plot the time line of wins/losses of India against Australia, West Indies, South Africa in away/neutral venues
#from 2000-01-01 to 2017-01-01
ca.plotTimelineofWinsLosses("indiaTest.csv",teamName="India",opposition=["Australia","West Indies","South Africa"],
                         homeOrAway=["away","neutral"], startDate="2000-01-01",endDate="2017-01-01")
#Plot the time line of wins/losses of Indian Test team from 1970 onwards
ca.plotTimelineofWinsLosses("indiaTest.csv",teamName="India",startDate="1970-01-01",endDate="2017-01-01")
```



## 3 ODI
The functions below perform analysis of ODI teams listed above

###3a. Wins vs Loss against opposition ODI teams
This function performs analysis of ODI teams against other teams at home/away or neutral venue.
**Note**:- The opposition can be a vector of opposition teams. Similarly homeOrAway can also be a vector of
home/away/neutral venues.

```{python odi1,cache=TRUE}
import cricpy.analytics as ca
# Get the performance of West Indies in ODIs against all other ODI teams at all venues and retirn as a dataframe
df = ca.teamWinLossStatusVsOpposition("westindiesODI.csv",teamName="West Indies",opposition=["all"],homeOrAway=["all"],matchType="ODI",plot=False)
print(df)

# Plot the performance of West Indies in ODIs against Sri Lanka, India at all venues
ca.teamWinLossStatusVsOpposition("westindiesODI.csv",teamName="West Indies",opposition=["Sri Lanka", "India"],homeOrAway=["all"],matchType="ODI",plot=True)

#Plot the performance of Ireland in ODIs against Zimbabwe, Kenya, bermuda, UAE, Oman and Scotland at all venues
ca.teamWinLossStatusVsOpposition("irelandODI.csv",teamName="Ireland",opposition=["Zimbabwe","Kenya","Bermuda","U.A.E.","Oman","Scotland"],homeOrAway=["all"],matchType="ODI",plot=True)

```


### 3b Wins vs losses of ODI teams against opposition at different venues
```{python odi2,cache=TRUE}
import cricpy.analytics as ca
# Plot the performance of England ODI team against Bangladesh, West Indies and Australia at all venues
ca.teamWinLossStatusAtGrounds("englandODI.csv",teamName="England",opposition=["West Indies"],homeOrAway=["all"],matchType="ODI",plot=True)

#Plot the performance of India against South Africa, West Indies and Australia at 'home' venues
ca.teamWinLossStatusAtGrounds("indiaODI.csv",teamName="India",opposition=["South Africa"],homeOrAway=["home"],matchType="ODI",plot=True)
```

###3c. Plot the time line of wins vs losses of ODI teams against opposition at different venues during an interval
```{python odi3, cache=TRUE}

import cricpy.analytics as ca
#Plot the time line of wins/losses of Bangladesh ODI team between 2015 and 2019 against all other teams and at
# all venues
ca.plotTimelineofWinsLosses("bangladeshOD.csv",teamName="Bangladesh",startDate="2015-01-01",endDate="2019-01-01",matchType="ODI")

#Plot the time line of wins/losses of India ODI against Sri Lanka, Bangladesh from 2016 to 2019
ca.plotTimelineofWinsLosses("indiaODI.csv",teamName="India",opposition=["Sri Lanka","Bangladesh"],startDate="2016-01-01",endDate="2019-01-01",matchType="ODI")

```

## 4 Twenty 20
The functions below perform analysis of Twenty 20  teams listed above

###4a. Wins vs Loss against opposition ODI teams
This function performs analysis of T20 teams against other T20 teams at home/away or neutral venue.
**Note**:- The opposition can be a list of opposition teams. Similarly homeOrAway can also be a list of home/away/neutral venues.

```{python t20, cache=TRUE}
import cricpy.analytics as ca
# Get the performance of South Africa T20 team against England, India and Sri Lanka at home grounds at England
df = ca.teamWinLossStatusVsOpposition("southafricaT20.csv",teamName="South Africa",opposition=["England","India","Sri Lanka"], homeOrAway=["home"], matchType="T20", plot=False)
print(df)

#Plot the performance of South Africa T20 against England, India and Sri Lanka at all venues
ca.teamWinLossStatusVsOpposition("southafricaT20.csv",teamName="South Africa", opposition=["England","India","Sri Lanka"],homeOrAway=["all"],matchType="T20",plot=True)

#Plot the performance of Afghanistan T20 teams against all oppositions
ca.teamWinLossStatusVsOpposition("afghanistanT20.csv",teamName="Afghanistan",opposition=["all"],homeOrAway=["all"],matchType="T20",plot=True)

```


### 4b Wins vs losses of T20 teams against opposition at different venues
```{python, t20-2,cache=TRUE}
import cricpy.analytics as ca
# Compute the performance of Canada against all opposition at all venues and show by grounds
df=ca.teamWinLossStatusAtGrounds("canadaT20.csv",teamName="Canada",opposition=["all"],homeOrAway=["all"],matchType="T20", plot=False)
print(df)

ca.teamWinLossStatusAtGrounds("srilanka20.csv",teamName="Sri Lanka",opposition=["India, Bangladesh"], homeOrAway=c("all"), matchType="T20", plot=True)

```

###4c. Plot the time line of wins vs losses of T20 teams against opposition at different venues during an interval

```{python, t20-2,cache=TRUE}
import cricpy.analytics as ca
#Plot the time line of Sri Lanka T20 team agaibst all opposition
ca.plotTimelineofWinsLosses("srilankaT20.csv",team="Sri Lanka",opposition=["Australia", "Pakistan"], startDate="2013-01-01", endDate="2019-01-01",  matchType="T20")

# Plot the time line of Bangladesh T20 between 2015 and 2017
ca.plotTimelineofWinsLosses("bangladesh.csv",team="Bangladesh",startDate="2015-01-01",endDate="2017-01-01")

ca.plotTimelineofWinsLosses("bangladesh.csv",team="Bangladesh",opposition=["Sri Lanka","India"))
```
